driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: rhel7
    driver_config:
      box: iamseth/rhel-7.3

suites:
  - name: default
    run_list:
      - recipe[rhsm_test::default]
    attributes:
      rhsm:
        activation_key: <%= ENV['rhsm_activation_key'] %>
        organization: <%= ENV['rhsm_organization'] %>
